active = "main"

[profiles.main]
PREFECT_LOGGING_LEVEL = "INFO"
PREFECT_SERVER_API_PORT = "4300"
PREFECT_API_URL = "http://127.0.0.1:4300/api"

[profiles.dev]
PREFECT_LOGGING_LEVEL = "DEBUG"
PREFECT_SERVER_API_PORT = "4309"
PREFECT_API_URL = "http://127.0.0.1:4309/api"
